export const FETCH_PEOPLE_LOADING = 'FETCH_PEOPLE_LOADING';
export const FETCH_PEOPLE_ERROR = 'FETCH_PEOPLE_ERROR';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_DETAIL = 'FETCH_PEOPLE_DETAIL';

export const FETCH_PLANET_LOADING = 'FETCH_PLANET_LOADING';
export const FETCH_PLANET_ERROR = 'FETCH_PLANET_ERROR';
export const FETCH_PLANET_SUCCESS = 'FETCH_PLANET_SUCCESS';
export const FETCH_PLANET_DETAIL = 'FETCH_PLANET_DETAIL';

export const FETCH_FILMS_LOADING = 'FETCH_FILMS_LOADING';
export const FETCH_FILMS_ERROR = 'FETCH_FILMS_ERROR';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_DETAIL = 'FETCH_FILMS_DETAIL';

export const FETCH_SPECIES_LOADING = 'FETCH_SPECIES_LOADING';
export const FETCH_SPECIES_ERROR = 'FETCH_SPECIES_ERROR';
export const FETCH_SPECIES_SUCCESS = 'FETCH_SPECIES_SUCCESS';
export const FETCH_SPECIES_DETAIL = 'FETCH_SPECIES_DETAIL';

export const FETCH_VEHICLES_LOADING = 'FETCH_VEHICLES_LOADING';
export const FETCH_VEHICLES_ERROR = 'FETCH_VEHICLES_ERROR';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_VEHICLES_DETAIL = 'FETCH_VEHICLES_DETAIL';

export const FETCH_STARSHIPS_LOADING = 'FETCH_STARSHIPS_LOADING';
export const FETCH_STARSHIPS_ERROR = 'FETCH_STARSHIPS_ERROR';
export const FETCH_STARSHIPS_SUCCESS = 'FETCH_STARSHIPS_SUCCESS';
export const FETCH_STARSHIPS_DETAIL = 'FETCH_STARSHIPS_DETAIL';